mcg: &mcg
  type: ModifiedCircleGridTargetFinder
  rows: 3
  cols: 4
  spacing: 0.050
  circle_detector_params:
    minThreshold: 20
    maxThreshold: 220
    nThresholds: 20

    minRepeatability: 3
    circleInclusionRadius: 5
    maxRadiusDiff: 5

    maxAverageEllipseError: 0.02

    filterByColor: true
    circleColor: 0

    filterByArea: true
    minArea: 500.0
    maxArea: 50000.0

    filterByCircularity: false
    minCircularity: 0.8
    maxCircularity: 99999999.0

    filterByInertia: false
    minInertiaRatio: 0.1
    maxInertiaRatio: 99999999.0

    filterByConvexity: true
    minConvexity: 0.95
    maxConvexity: 99999999.0

charuco: &charuco_7x5
  type: CharucoGridTargetFinder
  rows: 7
  cols: 5
  chessboard_dim: 0.035
  aruco_marker_dim: 0.027
  dictionary: 0  # DICT_4X4_250

charuco: &charuco_10x6
  type: CharucoGridTargetFinder
  rows: 10
  cols: 6
  chessboard_dim: 0.040
  aruco_marker_dim: 0.031
  dictionary: 0  # DICT_4X4_250

target_finder: *charuco_10x6
  
intrinsics:
  fx: 640.4694213867188
  fy: 638.9653930664062
  cx: 650.2816162109375
  cy: 360.88458251953125

homography_threshold: 2.0
static_camera: false

camera_mount_to_camera_guess:
  x: 0.071
  y: 0.095
  z: 0.030
  qx: 0.0
  qy: 0.0
  qz: 1.0
  qw: 0.0

target_mount_to_target_guess:
  x: 0.6
  y: 0.1
  z: 0.025
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 1.0
  
